controller_list:
  - name: fake_manipulator_controller
    joints:
      - j2n6a300_joint_1
      - j2n6a300_joint_2
      - j2n6a300_joint_3
      - j2n6a300_joint_4
      - j2n6a300_joint_5
      - j2n6a300_joint_6
  - name: fake_end_effector_controller
    joints:
      []