publish_frequency: 1.0

footprint: [[0.25, 0.0], [0.177, 0.177], [0.0,0.25], [-0.177, 0.177], [-0.25, 0.0], [-0.177, -0.177], [0.0, -0.25], [0.177, -0.177] ]

inflation_layer:
  inflation_radius: 0.3

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_laser
  front_laser:
    sensor_frame: robot_front_laser_link
    data_type: LaserScan
    topic: front_laser/scan
    marking: true
    clearing: true
    observation_persistence: 0.0

rgbd_obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_rgbd_to_scan
  front_rgbd_to_scan:
    data_type: LaserScan
    topic: front_rgbd_camera/point_cloud_scan_filtered
    marking: true
    clearing: true
    observation_persistence: 5.0

rgbd_head_obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: head_rgbd_to_scan
  head_rgbd_to_scan:
    sensor_frame: robot_torso_rgbd_camera_link
    data_type: LaserScan
    topic: torso_rgbd_camera/point_cloud_scan_filtered
    marking: true
    clearing: true
    observation_persistence: 5.0
