obstacle_range: 5.0
raytrace_range: 6.0
footprint: [[0.25, 0.0], [0.177, 0.177], [0.0,0.25], [-0.177, 0.177], [-0.25, 0.0], [-0.177, -0.177], [0.0, -0.25], [0.177, -0.177] ]
#footprint: [[0.260, 0.0], [0.187, 0.187], [0.0,0.260], [-0.187, 0.187], [-0.260, 0.0], [-0.187, -0.187], [0.0, -0.260], [0.187, -0.187] ]
#inflation_radius: 0.55
#inflation_radius: 0.10

obstacle_layer:
  observation_sources:  base_front_laser
  base_front_laser: {sensor_frame: rb1_base_front_laser_link, data_type: LaserScan, topic: front_laser/scan, marking: true, clearing: true, observation_persistence: 1.0}
  base_front_camera: {data_type: PointCloud2, topic: front_rgbd_camera/depth/points, marking: true, clearing: true, observation_persistence: 1.0, min_obstacle_height: 0.1}

