joint_blw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: rb1_left_wheel_joint
joint_brw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: rb1_right_wheel_joint

robotnik_base_control:
  type: rb1_controller/RB1BaseController
  joint:
    right_wheel_joint:
        name: rb1_right_wheel_joint
        max_speed: 27.27 # rad/s
    left_wheel_joint:
        name: rb1_left_wheel_joint
        max_speed: 27.27 # rad/s
  limits:
    # how to deccelerate in case of hard_brake. 
    hard_brake: 
      linear_speed_limit: 1.5 # m/s
      linear_acceleration_limit: 1.5 # m/s^2
      linear_deceleration_limit: 4 # m/s^2
      angular_speed_limit: 3 # rad/s
      angular_acceleration_limit: 3.0 # rad/s^2
      angular_deceleration_limit: 6.0 # rad/s^2
  # TODO: remove this parameter, as it will be controlled by the limits above
  hard_brake: false
  odom_frame: rb1_odom
  robot_base_frame: rb1_base_footprint
  odom_broadcast_tf: true
  odom_topic: 'robotnik_base_control/odom'
  track_width: 0.421 # 0.543
  wheel_diameter: 0.1524
  cmd_watchdog_duration: 0.5
  imu_watchdog_duration: 0.1
  imu_topic: 'imu/data'
  odom_publish_frequency: 100
  cmd_vel        : 'robotnik_base_control/cmd_vel'
  motion_odometry: true
  in_motion_timer: 2.0
  position_covariance: 0.0000001
  orientation_covariance: 0.0000001
  linear_velocity_covariance: 0.0000000001
  angular_velocity_covariance: 0.0000000001
  set_digital_output_service_hw: robotnik_base_hw/set_digital_output
  has_elevator: false
  reverse_logic: true # Make sure what logic is your robot using

joint_read_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 100.0



