topics:
- name    : pad
  topic   : pad_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 2
- name    : dockers
  topic   : dockers/cmd_vel
  timeout : 0.5
  priority: 2
- name    : move
  topic   : move/cmd_vel
  timeout : 0.5
  priority: 2 
#- name    : cart_docker
#  topic   : cart_docker/cmd_vel
#  timeout : 0.5
#  priority: 2 
#- name    : pp_docker
#  topic   : pp_docker/cmd_vel
#  timeout : 0.5
#  priority: 2  
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1

locks:
- name    : e_stop
  topic   : robotnik_base_hw/emergency_stop
  timeout : 0.0
  priority: 255
